# Generated by Django 3.2.10 on 2022-07-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_cover',
            field=models.ImageField(blank=True, null=True, upload_to='mangas/'),
        ),
    ]
